### ISSUE TITLE
github里面的和http://jiji262.github.io/wooyun_articles/  不一样啊

### ISSUE THREAD

**Issue by wujunze** [jiji262/wooyun_articles#2]
博主你好:
      我从你的github下载了wooyun这个代码   放在我的服务器上   页面的效果和你的http://jiji262.github.io/wooyun_articles/    不一样啊   我的https://wujunze.com/wooyun/drops/      是文件不完整吗?
麻烦看看
谢谢

**Comment by jiji262** [comment]
你的站点打不开。
应该是一样的，实在不行，你可以看到`http://jiji262.github.io/wooyun_articles/` 这页面所有源代码：
https://github.com/jiji262/wooyun_articles/tree/gh-pages

**Comment by wujunze** [comment]
可以打开  不过首页是空白  github里面的代码没有index.html  
https://wujunze.com/wooyun/drops/2014%E5%B9%B4%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A%E4%BF%A1%E6%81%AF%E5%AE%89%E5%85%A8%E6%8C%91%E6%88%98%20CySCA%20CTF%20%E5%AE%98%E6%96%B9write%20up%20Crypto%E7%AF%87.html    打开这个
